tastejs/hacker-news-pwas

- README.md
> Add repo for Preact example

- README.md
Mostly forked from Svelte HN version, the isomorphic [viperHTML](https://github.com/WebReflection/viperHTML) would like to join the list of blazing fast, Lighthouse friendly, possible library to create modern PWAs in a new, fully Web standard based, KISS way to update layouts.
> Add viperHTML to the list

- README.md
R: @housseindjirdeh @lukeed
issue: #9 
Wdyt? Is this better?
> Add more details to network settings used (#9)

- README.md
Adding reference to WPT `easy` in Network Settings section
> reference WPT easy settings under network settings section

- site/_contributors/chris.txt
> Add me as a contributor

- site/app.yaml
The path `/index.html` needs adding to the list of available assets I believe.
> Ensure index.html is available on prod

- site/_config.yml
- site/_includes/footer.html
- site/package.json
Adds analytics for #26
Also increased the width of the footer since we have more contributors now, gave it some more room :)
> add analytics, fix config attributes and increase width of footer

- README.md
Minor modifications, can see the changes [here](https://github.com/housseindjirdeh/hacker-news-pwas/tree/patch-readme) :man_dancing:
> add Travis CI build card to README + slight modifications

- site/_includes/implementation.html
- site/_layouts/home.html
http://hnpwa-is-nice-and-fresh.surge.sh
🎉
> move submit section to bottom + minor accessibility fixes

- CONTRIBUTING.md
- site/app.yaml
based on https://cloud.google.com/appengine/docs/standard/python/getting-started/hosting-a-static-website I've tested it using `dev_appserver.py` & it's working fine :)
> simplify GAE's url handlers

- site/_apps/preact-hn.txt
Update timings for Preact-HN after changes in hosting infrastructure.
> Update Preact-HN timings

- site/_apps/react-hn-kristofer.txt
Update timings for React-HN with changed base page serving infrastructure.
> Update React-HN timings

- site/_apps/svelte-hacker-news.txt
* Custom fonts have been removed making the application load faster on EM_3G.
* Is no longer using H2 Push.
* Lighthouse score has changed (manifest and accessibility)
> Update Svelte Hacker News timings

- site/_apps/polymer-hn.txt
Would be great to hear from the authors if there have been changes which improved performance.
> Update Polymer-HN timings

- site/_apps/angular-hn.txt
The `Redirects HTTP traffic to HTTPS` is still failing but once that's get resolved I'll update the LH score accordingly
> update Angular HN numbers

- site/_apps/viper-news.txt
Continuing to update based on latest Lighthouse.
> Update ViperHTML timings

- docs/api.md
Add documentation on the HNPWA API.
> Add HNPWA API docs

- site/_apps/react-hn-kristofer.txt
Smaller Bundle, React 16 rc3, Render props instead of HoC
> Update React-HN timing

- site/_apps/preact-hn.txt
https://github.com/kristoferbaxter/preact-hn/commit/25c2831d15e23fa29b1ecdf76891195b9af190e3
Reduced JS payload by ~2k uncompressed.
> Preact-HN Typescript

- site/_apps/viper-news.txt
viperHTML met Webpack today and it worked out pretty well 🎉
The timings updates are based on latest Lighthouse.
Best Regards.
> Update ViperHTML bundler + timings

- site/_apps/cycle-hn.txt
Fixes the missing framework and library names on the app listings.
> Fixes the framework and lib names

- site/_apps/dojo-2.txt
Update the lighthouse and interactive scores for the dojo hnpwa
> Dojo lighthouse and webpagetest score updates

- site/_apps/vue-hacker-news.txt
https://github.com/vuejs/vue-hackernews-2.0/commit/98399b55c6f1da4197840ba76189795b3e95be0f
> Update demo link `Vue Hacker News 2.0`
